// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Apollo from "./Apollo.js";
import * as HtmlTags from "./HtmlTags.js";
import * as Client from "@apollo/client";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx(Client.ApolloProvider, {
              client: Apollo.client,
              children: JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsx(HtmlTags.P.make, {
                          children: "Hello"
                        })
                  })
            });
}

var make = App;

export {
  make ,
}
/* Apollo Not a pure module */
